### PR TITLE
Validations

### LINKED ISSUE #21: Lack of form validation can lead to unexpected deployment failures
After submitting form data, each workflow step should verify the data is valid.

* For AWS credentials, perform an AWS-CLI function that requires credentials (like looking up the region list).
* For FQDN, verify the subdomain is a Route53 hosted zone, and verify the full FQDN is a valid URL.

### PR DESCRIPTION
**Pull request by jesusbv**
- Add AWS credentials validation
- Add FQDN and subdomain validation

This Fixes #21

### CODE REVIEW

File: engines/rancher_on_eks/app/models/rancher_on_eks/fqdn.rb [hunk 1]
```diff
@@ -14,5 +14,9 @@ def self.load
     def save!
       KeyValue.set(:fqdn, @value)
     end
+
+    def dns_available?
+      system("ping -c 1 -W 1 #{@value}")
```
Comment (jgleissner) [inline engines/rancher_on_eks/app/models/rancher_on_eks/fqdn.rb:19]: Not sure whether that's the best way to test whether DNS is available. The ping may fail due to other reasons than `@value` not being resolvable. The system may not be reachable, there may be packet loss, or ICMP traffic may be filtered. Wouldn't it make more sense to simply try to resolve the fqdn?

Comment (jesusbv) [reply engines/rancher_on_eks/app/models/rancher_on_eks/fqdn.rb:19]: Yes, I did not want to add a new Gem
it seems the library that does that is in the stdlib

Comment (smarlowucf) [reply engines/rancher_on_eks/app/models/rancher_on_eks/fqdn.rb:19]: I would have the same comment/question. Is Ruby similar to Python in terms of "ask for forgiveness"? Using a try/except style handling instead of lbyl?

File: engines/aws/app/controllers/aws/credentials_controller.rb [hunk 2]
```diff
@@ -6,14 +6,16 @@ def edit; end
...
+      valid_credentials = @credential.valid_credentials? self.credential_params
+      if valid_credentials && @credential.save
         flash[:success] = t(
           'engines.aws.credentials.using',
           key_id: @credential.aws_access_key_id
         )
         redirect_to(helpers.next_step_path(aws.edit_credential_path))
       else
-        flash[:warning] = @credential.errors.full_messages
+        flash[:warning] = @credential.errors.full_messages if valid_credentials
```
Comment (smarlowucf) [inline engines/aws/app/controllers/aws/credentials_controller.rb:17]: Formatting question: This is two clauses in one? Probabaly normal in Ruby syntax but from Python standpoint I would split everything out:

```
if not valid_credentials
  flash[:warning] = "Credentials are not valid."
elif not @credential.save
  flash[:warning] = @credential.errors.full_messages
else
  flash[:success] = t(
    'engines.aws.credentials.using',
    key_id: @credential.aws_access_key_id
  )
  redirect_to(helpers.next_step_path(aws.edit_credential_path))
end
```

**Review by smarlowucf — APPROVED** [review]
Looks good as best as I can tell.

File: engines/rancher_on_eks/app/models/rancher_on_eks/fqdn.rb (hunk 1 above)
Comment (jgleissner) [reply engines/rancher_on_eks/app/models/rancher_on_eks/fqdn.rb]: So couldn't the system('ping ...') call be replaced by something like Addrinfo.getaddrinfo()? That's in the stdlib AFAICS.

Comment (jesusbv) [reply engines/rancher_on_eks/app/models/rancher_on_eks/fqdn.rb]: @jgleissner I updated the code to the validations we had planned (valid URL and hosted zone for subdomain)

**Review by jgleissner — APPROVED** [review]
LGTM
